name: Regression End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'       

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests with Mochawesome
        run: |
          npx cypress run --reporter mochawesome \
                          --reporter-options reportDir=cypress/results,overwrite=false,html=false,json=true
        continue-on-error: true

      - name: Extract test summary
        if: always()
        run: |
          RESULTS_FILE="cypress/results/mochawesome.json"
          
          # Check if the results file exists to prevent errors
          if [ ! -f "$RESULTS_FILE" ]; then
            echo "WARNING: Mochawesome results file '$RESULTS_FILE' not found. Defaulting test counts to 0."
            echo "PASSED_TESTS=0" >> $GITHUB_ENV
            echo "FAILED_TESTS=0" >> $GITHUB_ENV
            echo "SKIPPED_TESTS=0" >> $GITHUB_ENV
            echo "TOTAL_TESTS=0" >> $GITHUB_ENV
            # Set default color if no report found (e.g., if Cypress failed to run at all)
            echo "SLACK_DYNAMIC_COLOR=danger" >> $GITHUB_ENV 
          else
            echo "PASSED_TESTS=$(jq '.stats.passes' "$RESULTS_FILE")" >> $GITHUB_ENV
            echo "FAILED_TESTS=$(jq '.stats.failures' "$RESULTS_FILE")" >> $GITHUB_ENV
            echo "SKIPPED_TESTS=$(jq '.stats.skipped' "$RESULTS_FILE")" >> $GITHUB_ENV
            echo "TOTAL_TESTS=$(jq '.stats.tests' "$RESULTS_FILE")" >> $GITHUB_ENV

            # Determine Slack color based on test failures
            if [ "$(jq '.stats.failures' "$RESULTS_FILE")" -gt 0 ]; then
              echo "SLACK_DYNAMIC_COLOR=danger" >> $GITHUB_ENV # Red for failures
            else
              echo "SLACK_DYNAMIC_COLOR=good" >> $GITHUB_ENV # Green for success
            fi
          fi

      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ env.SLACK_DYNAMIC_COLOR }} # Use the dynamically calculated color
          SLACK_USERNAME: CyNotification
          SLACK_ICON: https://pbs.twimg.com/profile_images/1512090708181725184/KAPAXmDg_400x400.jpg
          SLACK_MESSAGE: | # Multi-line block for desired formatting
            *Resultados de Pruebas Cypress* para el commit `<https://github.com/${{ github.repository }}/commit/${{ github.sha }}>` en la rama `${{ github.ref_name }}`
            
            📊 Total: ${{ env.TOTAL_TESTS }}
            ✅ Passed: ${{ env.PASSED_TESTS }}
            ❌ Failed: ${{ env.FAILED_TESTS }}
            ⚪️ Skipped: ${{ env.SKIPPED_TESTS }}
            🔗 Ver workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          SLACK_TITLE: Cypress Web Test
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}